package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:17:38 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private BigDecimal id;
	private String appName;
	private String appNameAbreviation;
	private Set businessrules = new HashSet(0);

	public Application() {
	}

	public Application(BigDecimal id, String appName, String appNameAbreviation) {
		this.id = id;
		this.appName = appName;
		this.appNameAbreviation = appNameAbreviation;
	}

	public Application(BigDecimal id, String appName,
			String appNameAbreviation, Set businessrules) {
		this.id = id;
		this.appName = appName;
		this.appNameAbreviation = appNameAbreviation;
		this.businessrules = businessrules;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getAppNameAbreviation() {
		return this.appNameAbreviation;
	}

	public void setAppNameAbreviation(String appNameAbreviation) {
		this.appNameAbreviation = appNameAbreviation;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
