package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:17:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BackEndRuleType generated by hbm2java
 */
public class BackEndRuleType implements java.io.Serializable {

	private String name;
	private Set businessrules = new HashSet(0);
	private Set operators = new HashSet(0);

	public BackEndRuleType() {
	}

	public BackEndRuleType(String name) {
		this.name = name;
	}

	public BackEndRuleType(String name, Set businessrules, Set operators) {
		this.name = name;
		this.businessrules = businessrules;
		this.operators = operators;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

	public Set getOperators() {
		return this.operators;
	}

	public void setOperators(Set operators) {
		this.operators = operators;
	}

}
