package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:17:38 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Businessrule generated by hbm2java
 */
public class Businessrule implements java.io.Serializable {

	private BigDecimal id;
	private BackEndRuleType backEndRuleType;
	private FrontEndRuletype frontEndRuletype;
	private Application application;
	private Businessrule businessrule;
	private Value value;
	private Operator operator;
	private String name;
	private String description;
	private Set businessrules = new HashSet(0);
	private Set generatedcodes = new HashSet(0);
	private Set values = new HashSet(0);

	public Businessrule() {
	}

	public Businessrule(BigDecimal id, BackEndRuleType backEndRuleType,
			FrontEndRuletype frontEndRuletype, Application application,
			Value value, Operator operator, String name) {
		this.id = id;
		this.backEndRuleType = backEndRuleType;
		this.frontEndRuletype = frontEndRuletype;
		this.application = application;
		this.value = value;
		this.operator = operator;
		this.name = name;
	}

	public Businessrule(BigDecimal id, BackEndRuleType backEndRuleType,
			FrontEndRuletype frontEndRuletype, Application application,
			Businessrule businessrule, Value value, Operator operator,
			String name, String description, Set businessrules,
			Set generatedcodes, Set values) {
		this.id = id;
		this.backEndRuleType = backEndRuleType;
		this.frontEndRuletype = frontEndRuletype;
		this.application = application;
		this.businessrule = businessrule;
		this.value = value;
		this.operator = operator;
		this.name = name;
		this.description = description;
		this.businessrules = businessrules;
		this.generatedcodes = generatedcodes;
		this.values = values;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BackEndRuleType getBackEndRuleType() {
		return this.backEndRuleType;
	}

	public void setBackEndRuleType(BackEndRuleType backEndRuleType) {
		this.backEndRuleType = backEndRuleType;
	}

	public FrontEndRuletype getFrontEndRuletype() {
		return this.frontEndRuletype;
	}

	public void setFrontEndRuletype(FrontEndRuletype frontEndRuletype) {
		this.frontEndRuletype = frontEndRuletype;
	}

	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	public Businessrule getBusinessrule() {
		return this.businessrule;
	}

	public void setBusinessrule(Businessrule businessrule) {
		this.businessrule = businessrule;
	}

	public Value getValue() {
		return this.value;
	}

	public void setValue(Value value) {
		this.value = value;
	}

	public Operator getOperator() {
		return this.operator;
	}

	public void setOperator(Operator operator) {
		this.operator = operator;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

	public Set getGeneratedcodes() {
		return this.generatedcodes;
	}

	public void setGeneratedcodes(Set generatedcodes) {
		this.generatedcodes = generatedcodes;
	}

	public Set getValues() {
		return this.values;
	}

	public void setValues(Set values) {
		this.values = values;
	}

}
