package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:39:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * FrontEndRuletype generated by hbm2java
 */
public class FrontEndRuletype implements java.io.Serializable {

	private String name;
	private String abbreviation;
	private Set businessrules = new HashSet(0);

	public FrontEndRuletype() {
	}

	public FrontEndRuletype(String name) {
		this.name = name;
	}

	public FrontEndRuletype(String name, String abbreviation, Set businessrules) {
		this.name = name;
		this.abbreviation = abbreviation;
		this.businessrules = businessrules;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
