package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:39:21 PM by Hibernate Tools 4.0.0

import java.sql.Clob;

/**
 * Generatedcode generated by hbm2java
 */
public class Generatedcode implements java.io.Serializable {

	private GeneratedcodeId id;
	private Businessrule businessrule;
	private Language language;
	private Clob businessRuleCode;

	public Generatedcode() {
	}

	public Generatedcode(GeneratedcodeId id, Businessrule businessrule,
			Language language) {
		this.id = id;
		this.businessrule = businessrule;
		this.language = language;
	}

	public Generatedcode(GeneratedcodeId id, Businessrule businessrule,
			Language language, Clob businessRuleCode) {
		this.id = id;
		this.businessrule = businessrule;
		this.language = language;
		this.businessRuleCode = businessRuleCode;
	}

	public GeneratedcodeId getId() {
		return this.id;
	}

	public void setId(GeneratedcodeId id) {
		this.id = id;
	}

	public Businessrule getBusinessrule() {
		return this.businessrule;
	}

	public void setBusinessrule(Businessrule businessrule) {
		this.businessrule = businessrule;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Clob getBusinessRuleCode() {
		return this.businessRuleCode;
	}

	public void setBusinessRuleCode(Clob businessRuleCode) {
		this.businessRuleCode = businessRuleCode;
	}

}
