package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:39:21 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * GeneratedcodeId generated by hbm2java
 */
public class GeneratedcodeId implements java.io.Serializable {

	private BigDecimal businessruleId;
	private String languageName;

	public GeneratedcodeId() {
	}

	public GeneratedcodeId(BigDecimal businessruleId, String languageName) {
		this.businessruleId = businessruleId;
		this.languageName = languageName;
	}

	public BigDecimal getBusinessruleId() {
		return this.businessruleId;
	}

	public void setBusinessruleId(BigDecimal businessruleId) {
		this.businessruleId = businessruleId;
	}

	public String getLanguageName() {
		return this.languageName;
	}

	public void setLanguageName(String languageName) {
		this.languageName = languageName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GeneratedcodeId))
			return false;
		GeneratedcodeId castOther = (GeneratedcodeId) other;

		return ((this.getBusinessruleId() == castOther.getBusinessruleId()) || (this
				.getBusinessruleId() != null
				&& castOther.getBusinessruleId() != null && this
				.getBusinessruleId().equals(castOther.getBusinessruleId())))
				&& ((this.getLanguageName() == castOther.getLanguageName()) || (this
						.getLanguageName() != null
						&& castOther.getLanguageName() != null && this
						.getLanguageName().equals(castOther.getLanguageName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getBusinessruleId() == null ? 0 : this.getBusinessruleId()
						.hashCode());
		result = 37
				* result
				+ (getLanguageName() == null ? 0 : this.getLanguageName()
						.hashCode());
		return result;
	}

}
