package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:17:38 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private String name;
	private Set generatedcodes = new HashSet(0);

	public Language() {
	}

	public Language(String name) {
		this.name = name;
	}

	public Language(String name, Set generatedcodes) {
		this.name = name;
		this.generatedcodes = generatedcodes;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getGeneratedcodes() {
		return this.generatedcodes;
	}

	public void setGeneratedcodes(Set generatedcodes) {
		this.generatedcodes = generatedcodes;
	}

}
