package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:39:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Operator generated by hbm2java
 */
public class Operator implements java.io.Serializable {

	private String name;
	private Set backEndRuleTypes = new HashSet(0);
	private Set businessrules = new HashSet(0);

	public Operator() {
	}

	public Operator(String name) {
		this.name = name;
	}

	public Operator(String name, Set backEndRuleTypes, Set businessrules) {
		this.name = name;
		this.backEndRuleTypes = backEndRuleTypes;
		this.businessrules = businessrules;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBackEndRuleTypes() {
		return this.backEndRuleTypes;
	}

	public void setBackEndRuleTypes(Set backEndRuleTypes) {
		this.backEndRuleTypes = backEndRuleTypes;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
