package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:39:21 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Valuetype generated by hbm2java
 */
public class Valuetype implements java.io.Serializable {

	private String name;
	private Set values = new HashSet(0);

	public Valuetype() {
	}

	public Valuetype(String name) {
		this.name = name;
	}

	public Valuetype(String name, Set values) {
		this.name = name;
		this.values = values;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getValues() {
		return this.values;
	}

	public void setValues(Set values) {
		this.values = values;
	}

}
