package com.r00lerz.businessRuleGenerator.domain.datamodel;

// Generated Apr 3, 2014 3:17:38 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Value generated by hbm2java
 */
public class Value implements java.io.Serializable {

	private BigDecimal id;
	private Businessrule businessrule;
	private Valuetype valuetype;
	private String value;
	private Set businessrules = new HashSet(0);

	public Value() {
	}

	public Value(BigDecimal id, Businessrule businessrule, Valuetype valuetype,
			String value) {
		this.id = id;
		this.businessrule = businessrule;
		this.valuetype = valuetype;
		this.value = value;
	}

	public Value(BigDecimal id, Businessrule businessrule, Valuetype valuetype,
			String value, Set businessrules) {
		this.id = id;
		this.businessrule = businessrule;
		this.valuetype = valuetype;
		this.value = value;
		this.businessrules = businessrules;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Businessrule getBusinessrule() {
		return this.businessrule;
	}

	public void setBusinessrule(Businessrule businessrule) {
		this.businessrule = businessrule;
	}

	public Valuetype getValuetype() {
		return this.valuetype;
	}

	public void setValuetype(Valuetype valuetype) {
		this.valuetype = valuetype;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
