/*
 * generated by Xtext
 */
package com.r00lerz.ruleDef;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RuleDefRuntimeModule extends com.r00lerz.ruleDef.AbstractRuleDefRuntimeModule {

}
