grammar com.r00lerz.ruleDef.RuleDef with org.eclipse.xtext.common.Terminals

generate ruleDef "http://www.r00lerz.com/ruleDefLang/RuleDef"

BusinessRule:
	columnvalue = ColumnValue ' ' operator = Operator ' ' value = Value
;
	
Value:
	StaticValue |  ColumnValue
;

ColumnValue:
	tablename = TableName'.' columname = ColumnName
;

ColumnName:
	name=ID
;

TableName:
	name=ID
;

StaticValue:
	name=INT
;

Operator:
	name = ('bigger than' | 'smaller than')
;