/*
* generated by Xtext
*/
package com.r00lerz.ruleDef.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RuleDefAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/r00lerz/ruleDef/parser/antlr/internal/InternalRuleDef.tokens");
	}
}
