/*
* generated by Xtext
*/
package com.r00lerz.ruleDef.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.r00lerz.ruleDef.services.RuleDefGrammarAccess;

public class RuleDefParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RuleDefGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.r00lerz.ruleDef.parser.antlr.internal.InternalRuleDefParser createParser(XtextTokenStream stream) {
		return new com.r00lerz.ruleDef.parser.antlr.internal.InternalRuleDefParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public RuleDefGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RuleDefGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
