/*
 * generated by Xtext
 */
package com.r00lerz.ruleDef.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.r00lerz.ruleDef.ui.internal.RuleDefActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RuleDefExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RuleDefActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RuleDefActivator.getInstance().getInjector(RuleDefActivator.COM_R00LERZ_RULEDEF_RULEDEF);
	}
	
}
