/*
 * generated by Xtext
 */
package com.r00lerz.ruleDef.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRuleDefValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.r00lerz.ruleDef.ruleDef.RuleDefPackage.eINSTANCE);
		return result;
	}
}
