package newlyGenerated;

// default package
// Generated 3-apr-2014 2:03:25 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Application generated by hbm2java
 */
public class Application implements java.io.Serializable {

	private BigDecimal id;
	private String brgName;
	private String brgNameAbreviation;
	private String appName;
	private String appNameAbreviation;
	private Set businessrules = new HashSet(0);

	public Application() {
	}

	public Application(BigDecimal id, String brgName,
			String brgNameAbreviation, String appName, String appNameAbreviation) {
		this.id = id;
		this.brgName = brgName;
		this.brgNameAbreviation = brgNameAbreviation;
		this.appName = appName;
		this.appNameAbreviation = appNameAbreviation;
	}

	public Application(BigDecimal id, String brgName,
			String brgNameAbreviation, String appName,
			String appNameAbreviation, Set businessrules) {
		this.id = id;
		this.brgName = brgName;
		this.brgNameAbreviation = brgNameAbreviation;
		this.appName = appName;
		this.appNameAbreviation = appNameAbreviation;
		this.businessrules = businessrules;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getBrgName() {
		return this.brgName;
	}

	public void setBrgName(String brgName) {
		this.brgName = brgName;
	}

	public String getBrgNameAbreviation() {
		return this.brgNameAbreviation;
	}

	public void setBrgNameAbreviation(String brgNameAbreviation) {
		this.brgNameAbreviation = brgNameAbreviation;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getAppNameAbreviation() {
		return this.appNameAbreviation;
	}

	public void setAppNameAbreviation(String appNameAbreviation) {
		this.appNameAbreviation = appNameAbreviation;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
