package newlyGenerated;

// default package
// Generated 3-apr-2014 2:03:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * BackEndRuleType generated by hbm2java
 */
public class BackEndRuleType implements java.io.Serializable {

	private String name;
	private Set businessrules = new HashSet(0);

	public BackEndRuleType() {
	}

	public BackEndRuleType(String name) {
		this.name = name;
	}

	public BackEndRuleType(String name, Set businessrules) {
		this.name = name;
		this.businessrules = businessrules;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
