package newlyGenerated;
// Generated 3-apr-2014 2:03:25 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Operator generated by hbm2java
 */
public class Operator implements java.io.Serializable {

	private String name;
	private Set frontEndRuletypes = new HashSet(0);
	private Set businessrules = new HashSet(0);

	public Operator() {
	}

	public Operator(String name) {
		this.name = name;
	}

	public Operator(String name, Set frontEndRuletypes, Set businessrules) {
		this.name = name;
		this.frontEndRuletypes = frontEndRuletypes;
		this.businessrules = businessrules;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getFrontEndRuletypes() {
		return this.frontEndRuletypes;
	}

	public void setFrontEndRuletypes(Set frontEndRuletypes) {
		this.frontEndRuletypes = frontEndRuletypes;
	}

	public Set getBusinessrules() {
		return this.businessrules;
	}

	public void setBusinessrules(Set businessrules) {
		this.businessrules = businessrules;
	}

}
