package newlyGenerated;

import java.math.BigDecimal;
import java.util.ArrayList;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import com.r00lerz.businessRuleGenerator.domain.datamodel.Application;
import com.r00lerz.businessRuleGenerator.domain.datamodel.BusinessRule;

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private BigDecimal id;
	private String naam;

	public Test() {
	}

	public Test(BigDecimal id) {
		this.id = id;
	}

	public Test(BigDecimal id, String naam) {
		this.id = id;
		this.naam = naam;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getNaam() {
		return this.naam;
	}

	public void setNaam(String naam) {
		this.naam = naam;
	}

}


