/*
* generated by Xtext
*/
package com.r00lerz.ruleDef.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.r00lerz.ruleDef.services.RuleDefGrammarAccess;

public class RuleDefParser extends AbstractContentAssistParser {
	
	@Inject
	private RuleDefGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.r00lerz.ruleDef.ui.contentassist.antlr.internal.InternalRuleDefParser createParser() {
		com.r00lerz.ruleDef.ui.contentassist.antlr.internal.InternalRuleDefParser result = new com.r00lerz.ruleDef.ui.contentassist.antlr.internal.InternalRuleDefParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
					put(grammarAccess.getOperatorAccess().getOperatorNameAlternatives_0(), "rule__Operator__OperatorNameAlternatives_0");
					put(grammarAccess.getBusinessRuleAccess().getGroup(), "rule__BusinessRule__Group__0");
					put(grammarAccess.getColumnValueAccess().getGroup(), "rule__ColumnValue__Group__0");
					put(grammarAccess.getBusinessRuleAccess().getColumnvalueAssignment_0(), "rule__BusinessRule__ColumnvalueAssignment_0");
					put(grammarAccess.getBusinessRuleAccess().getOperatorAssignment_2(), "rule__BusinessRule__OperatorAssignment_2");
					put(grammarAccess.getBusinessRuleAccess().getValueAssignment_4(), "rule__BusinessRule__ValueAssignment_4");
					put(grammarAccess.getValueAccess().getValueAssignment_0(), "rule__Value__ValueAssignment_0");
					put(grammarAccess.getColumnValueAccess().getTablenameAssignment_0(), "rule__ColumnValue__TablenameAssignment_0");
					put(grammarAccess.getColumnValueAccess().getColumnameAssignment_2(), "rule__ColumnValue__ColumnameAssignment_2");
					put(grammarAccess.getColumnNameAccess().getNameAssignment(), "rule__ColumnName__NameAssignment");
					put(grammarAccess.getTableNameAccess().getNameAssignment(), "rule__TableName__NameAssignment");
					put(grammarAccess.getStaticValueAccess().getNameAssignment(), "rule__StaticValue__NameAssignment");
					put(grammarAccess.getOperatorAccess().getOperatorNameAssignment(), "rule__Operator__OperatorNameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.r00lerz.ruleDef.ui.contentassist.antlr.internal.InternalRuleDefParser typedParser = (com.r00lerz.ruleDef.ui.contentassist.antlr.internal.InternalRuleDefParser) parser;
			typedParser.entryRuleBusinessRule();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RuleDefGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RuleDefGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
