/**
 * generated by Xtext
 */
package com.r00lerz.ruleDef.validation;

import com.r00lerz.ruleDef.validation.AbstractRuleDefValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RuleDefValidator extends AbstractRuleDefValidator {
}
