/*
* generated by Xtext
*/
package com.r00lerz.ruleDef;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RuleDefUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.r00lerz.ruleDef.ui.internal.RuleDefActivator.getInstance().getInjector("com.r00lerz.ruleDef.RuleDef");
	}
	
}
