/*
 * generated by Xtext
 */
package com.r00lerz.ruleDef.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RuleDefUiModule extends com.r00lerz.ruleDef.ui.AbstractRuleDefUiModule {
	public RuleDefUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
